# frozen_string_literal: true

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/core'
tap 'teamookla/speedtest'

brew 'aspell'
brew 'bash'
brew 'brew-cask-completion'
brew 'cabal-install'
brew 'coreutils'
brew 'dnsmasq'
brew 'dos2unix'
brew 'doxygen'
brew 'exiftool'
brew 'ffmpeg'
brew 'fish'
brew 'fzf'
brew 'gdb'
brew 'ghostscript'
brew 'git'
brew 'git-lfs'
brew 'go'
brew 'graphviz'
brew 'haskell-stack'
brew 'hub'
brew 'imagemagick'
brew 'jq'
brew 'libssh2'
brew 'libzip'
brew 'mas'
brew 'mhash'
brew 'nkf'
brew 'openssl'
brew 'openvpn'
brew 'pandoc'
brew 'pipenv'
brew 'popt'
brew 'pypy3'
brew 'r'
brew 'redis'
brew 'rustup-init'
brew 'speedtest'
brew 'telnet'
brew 'thefuck'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'unibilium'
brew 'vim'
brew 'yarn'
brew 'yq'

cask 'authy'
cask 'clipy'
cask 'discord'
cask 'docker'
cask 'firefox'
cask 'font-cascadia'
cask 'font-fira-code'
cask 'font-fira-mono'
cask 'github'
cask 'google-chrome'
cask 'gpg-suite-no-mail'
cask 'gyazo'
cask 'karabiner-elements'
cask 'keybase'
cask 'mactex-no-gui'
cask 'microsoft-edge'
cask 'rstudio'
cask 'swimat'
cask 'tor-browser'
cask 'vagrant'
cask 'visual-studio-code'

mas 'Kindle', id: 405_399_194
mas 'The Unarchiver', id: 425_424_353
mas 'Magnet', id: 441_258_766
mas 'Microsoft Word', id: 462_054_704
mas 'Microsoft Excel', id: 462_058_435
mas 'Microsoft PowerPoint', id: 462_062_816
mas 'Xcode', id: 497_799_835
mas 'LINE', id: 539_883_307
mas 'Slack', id: 803_453_959
mas 'Bear', id: 1_091_189_122
mas '1Password 7', id: 1_333_542_190
