brew:
  homebrew/core:
    - aspell
    - bash
    - cmake
    - coreutils
    - curl
    - dnsmasq
    - doxygen
    - fish
    - gdb
    - ghostscript
    - git
    - git-lfs
    - hub
    - imagemagick
    - jq
    - mas
    - nkf
    - node
    - peco
    - pipenv
    - pypy3
    - r
    - redis
    - tig
    - tmux
    - tree
    - vim
    - yq
  thoughtbot/formulae:
    - gitsh
mas:
  405399194: Kindle
  409183694: Keynote
  409201541: Pages
  409203825: Numbers
  441258766: Magnet
  462054704: Microsoft Word
  462058435: Microsoft Excel
  462062816: Microsoft PowerPoint
  497799835: Xcode
  539883307: LINE
  1024640650: CotEditor
  1091189122: Bear
  1333542190: 1Password 7
