unbind C-b
set-option -g prefix C-t

set-window-option -g window-status-current-style bg=magenta

set-option -g default-terminal "tmux-256color"
set-option -g terminal-overrides ",xterm-256color:RGB"
